#!/usr/bin/env bash
pio -f -c atom device monitor --raw --port /dev/ttyUSB0 -b 250000
#pio -f -c atom device monitor --raw --port /dev/ttyUSB0 -b 500000
#pio -f -c atom device monitor --raw --port /dev/ttyUSB0 -b 1000000
